//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Socios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public long Cedula { get; set; }
        public string Foto { get; set; }
        public string Direccion { get; set; }
        public long Telefono { get; set; }
        public string Sexo { get; set; }
        public int Edad { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Afiliados { get; set; }
        public string Membresia { get; set; }
        public string Lugar_Trabajo { get; set; }
        public string Direc_Oficina { get; set; }
        public Nullable<long> Tel_Oficina { get; set; }
        public string Estatus { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
